name: Deploy to Remote Server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

#    services:
#      docker:
#        image: docker:20.10-dind
#        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3

#      - name: Install Docker Compose
#        run: |
#          COMPOSE_VERSION=$(curl --silent "https://api.github.com/repos/docker/compose/releases/latest" | jq -r .tag_name)
#          sudo curl -L "https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#
#      - name: Build Docker image
#        run: docker-compose build
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Push Docker image
#        run: |
#          docker tag myspringboot2:latest ${{ secrets.DOCKERHUB_USERNAME }}/myspringboot2:latest
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myspringboot2:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | sed 's/\r$//' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.35.103 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files and deploy
        run: |
          scp -rv . daeun@192.168.35.103:/C/Users/Daeun/deploy
          ssh -v daeun@192.168.35.103 'cd /C/Users/Daeun/deploy && docker-compose up -d --build'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
