name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3
        with:
          version: '2.7.0'

      - name: Build Docker image
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose exec -T application ./gradlew test

      - name: Stop services
        run: docker-compose down

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag myspringboot:latest ${{ secrets.DOCKERHUB_USERNAME }}/myspringboot:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myspringboot:latest
